
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef PDO_MASTER_H
#define PDO_MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 PDO_Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * PDO_Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data PDO_Master_Data;
//extern UNS8 Master_ReceiveData[20];		/* Mapped at index 0x2000, subindex 0x01 - 0x14 */
//extern UNS8 Master_TransmitData[20];		/* Mapped at index 0x2001, subindex 0x01 - 0x14 */

#endif // PDO_MASTER_H
