
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef PDO_MASTER_H
#define PDO_MASTER_H

#include "canopen_data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 PDO_Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * PDO_Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data PDO_Master_Data;
extern UNS8 Master_ReceiveData_Master_ReceiveData_1;		/* Mapped at index 0x2000, subindex 0x01 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_2;		/* Mapped at index 0x2000, subindex 0x02 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_3;		/* Mapped at index 0x2000, subindex 0x03 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_4;		/* Mapped at index 0x2000, subindex 0x04 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_5;		/* Mapped at index 0x2000, subindex 0x05 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_6;		/* Mapped at index 0x2000, subindex 0x06 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_7;		/* Mapped at index 0x2000, subindex 0x07 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_8;		/* Mapped at index 0x2000, subindex 0x08 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_9;		/* Mapped at index 0x2000, subindex 0x09 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_10;		/* Mapped at index 0x2000, subindex 0x0A */
extern UNS8 Master_ReceiveData_Master_ReceiveData_11;		/* Mapped at index 0x2000, subindex 0x0B */
extern UNS8 Master_ReceiveData_Master_ReceiveData_12;		/* Mapped at index 0x2000, subindex 0x0C */
extern UNS8 Master_ReceiveData_Master_ReceiveData_13;		/* Mapped at index 0x2000, subindex 0x0D */
extern UNS8 Master_ReceiveData_Master_ReceiveData_14;		/* Mapped at index 0x2000, subindex 0x0E */
extern UNS8 Master_ReceiveData_Master_ReceiveData_15;		/* Mapped at index 0x2000, subindex 0x0F */
extern UNS8 Master_ReceiveData_Master_ReceiveData_16;		/* Mapped at index 0x2000, subindex 0x10 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_17;		/* Mapped at index 0x2000, subindex 0x11 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_18;		/* Mapped at index 0x2000, subindex 0x12 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_19;		/* Mapped at index 0x2000, subindex 0x13 */
extern UNS8 Master_ReceiveData_Master_ReceiveData_20;		/* Mapped at index 0x2000, subindex 0x14 */
extern UNS8 Master_TransmitData_Master_TransmitData_1;		/* Mapped at index 0x2001, subindex 0x01 */
extern UNS8 Master_TransmitData_Master_TransmitData_2;		/* Mapped at index 0x2001, subindex 0x02 */
extern UNS8 Master_TransmitData_Master_TransmitData_3;		/* Mapped at index 0x2001, subindex 0x03 */
extern UNS8 Master_TransmitData_Master_TransmitData_4;		/* Mapped at index 0x2001, subindex 0x04 */
extern UNS8 Master_TransmitData_Master_TransmitData_5;		/* Mapped at index 0x2001, subindex 0x05 */
extern UNS8 Master_TransmitData_Master_TransmitData_6;		/* Mapped at index 0x2001, subindex 0x06 */
extern UNS8 Master_TransmitData_Master_TransmitData_7;		/* Mapped at index 0x2001, subindex 0x07 */
extern UNS8 Master_TransmitData_Master_TransmitData_8;		/* Mapped at index 0x2001, subindex 0x08 */
extern UNS8 Master_TransmitData_Master_TransmitData_9;		/* Mapped at index 0x2001, subindex 0x09 */
extern UNS8 Master_TransmitData_Master_TransmitData_10;		/* Mapped at index 0x2001, subindex 0x0A */
extern UNS8 Master_TransmitData_Master_TransmitData_11;		/* Mapped at index 0x2001, subindex 0x0B */
extern UNS8 Master_TransmitData_Master_TransmitData_12;		/* Mapped at index 0x2001, subindex 0x0C */
extern UNS8 Master_TransmitData_Master_TransmitData_13;		/* Mapped at index 0x2001, subindex 0x0D */
extern UNS8 Master_TransmitData_Master_TransmitData_14;		/* Mapped at index 0x2001, subindex 0x0E */
extern UNS8 Master_TransmitData_Master_TransmitData_15;		/* Mapped at index 0x2001, subindex 0x0F */
extern UNS8 Master_TransmitData_Master_TransmitData_16;		/* Mapped at index 0x2001, subindex 0x10 */
extern UNS8 Master_TransmitData_Master_TransmitData_17;		/* Mapped at index 0x2001, subindex 0x11 */
extern UNS8 Master_TransmitData_Master_TransmitData_18;		/* Mapped at index 0x2001, subindex 0x12 */
extern UNS8 Master_TransmitData_Master_TransmitData_19;		/* Mapped at index 0x2001, subindex 0x13 */
extern UNS8 Master_TransmitData_Master_TransmitData_20;		/* Mapped at index 0x2001, subindex 0x14 */

#endif // PDO_MASTER_H
